---
title: "viz_part_02"
author: "Jasmine Niu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#theme_set(theme_minimal() + theme(legend.position = "bottom"))

#options(
#  ggplot2.continuous.colour = "viridis",
#  ggplot2.continuous.fill = "viridis")

#scale_colour_discrete = scale_colour_viridis_d
#scale_fill_discrete = scale_fill_viridis_d
                    
```

## Let's import data

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
```



```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## scatterplot

```{r}
ggp_weather = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    x = "Minimum Daily Temp (C)",
    y = "Maximum Daily Temp (C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package"
    ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15ºC", "0", "15"),
    limits = c(-20, 30)) +
  scale_y_continuous(
    trans = "sqrt",
    position = "right") +
  #scale_color_hue(name = "Location", h = c(100, 300))
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) 
```

## Themes


```{r}
ggp_weather +
  # theme(legend.position = "bottom") #legend.position = "none"
   theme_bw() +
  # theme_classic() +
  #theme_minimal() +
  theme(legend.position = "bottom") #少了theme_bw()
```

Learning assessment:

```{r}
ggp_weather2 =
  weather_df %>% 
  ggplot(aes(x = date, y = tmax)) +
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Scatterplot of Seasonal Trends",
    x = "Date",
    y = "Maximum Daily Temp (C)",
    caption = "Data come from the rnoaa package") +
  scale_y_continuous(
    breaks = c(-10, 0, 10, 20, 30),
    labels = c("-10ºC", "0", "10", "20", "30")) +
  theme_bw() +
  theme(legend.position = "bottom")

# Solution
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) + 
  geom_point(aes(size = prcp), alpha = .75) + 
  labs(
    title = "Temperature plot",
    x = "Date",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(discrete = TRUE) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```



## Data in geom()

```{r}
central_park_df =
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki_df =
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(waikiki_df, aes(x = date, y= tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park_df)
```

## Patchwork ...(unfinished)

```{r}
tmax_tmin_plot =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")
  

prcp_density_plot =
  weather_df %>% 
  filter(prcp >0) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
  theme(legend.position = "none")

tmax_date_plot =
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")

(tmax_tmin_plot + prcp_density_plot) / tmax_date_plot
```


## Data manipulation

```{r}
weather_df %>% 
  mutate(name = fct_reorder(name, tmax)) %>% #reorder by tmax's medium
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```


```{r}
pulse_df =
  haven::read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  select(id, visit, everything()) %>% 
  mutate(
    visit = fct_relevel(visit, "bl")
  )

pulse_df %>% 
  ggplot(aes(x = visit, y= bdi)) +
  geom_boxplot()
```

