---
title: "viz_part_01"
author: "Jasmine Niu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "80%"
  )
```

## Let's import data

```{r}
library(tidyverse)
library(ggridges)
```



```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode( #增加變數
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything()) #排列
```


Let's make a scatterplot.

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```



```{r}
weather_df %>% 
  drop_na() %>% 
  filter(name == "CentralPark_NY") %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


```{r}
weather_scatterplot =
  weather_df %>% 
  drop_na() %>% #去掉NA
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

weather_scatterplot +
  geom_point()
```

Fancy the plot.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y=tmax, color = name)) +
  geom_point()
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y=tmax, color = name)) +
  geom_point() +
  geom_smooth()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y=tmax)) +
  geom_point(aes(color = name)) +
  geom_smooth()
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y=tmax, color = name)) +
  geom_point(alpha = .3) + #alpha -> transparent
  geom_smooth(se = FALSE)
```

Make separate panels.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y=tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
# facet_grid(name ~ .)->橫向的圖
```


`tmax` vs `tmin`, split it up.

e.g. seasonal trend

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```

## Some quick stuff

Learning assessment!

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * 9/5 + 32, 
    tmin_fahr = tmin * 9/5 + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_hex()
```


```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```


## Univariate plots

Histogram

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid((. ~ name))
```

density plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + #color = name
  geom_density(alpha = .3, adjust = .5, color = "blue")
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, color = name)) + 
  geom_density(alpha = .3) +
  geom_rug()
```


boxplots

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_boxplot()
```

violin plots

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()
```

ridge plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

Learning assessment:

```{r}
ggplot(weather_df, aes(x = prcp, fill = name)) +
  geom_histogram(position = "dodge", binwidth = 50)
ggplot(weather_df, aes(x = prcp)) +
  geom_density(aes(fill = name), alpha = .5)
ggplot(weather_df, aes(x = name, y = prcp)) + geom_boxplot()
ggplot(weather_df, aes(x = name, y = prcp)) +
  geom_violin(aes(fill = name), alpha = .5) +
  stat_summary(fun = "median", color = "blue")
ggplot(weather_df, aes(x = prcp, y = name)) + #x,y要反過來
  geom_density_ridges(scale = .85)

weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, y = name)) + 
  geom_density_ridges(scale = .85)

weather_df %>% 
  filter(prcp >0) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5)
```


## Saving and embedding plots

```{r}
weather_scatterplot = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)

weather_scatterplot

ggsave("results/weather_scatterplot.pdf", weather_scatterplot,
       width = 8, height = 5)
```

```{r, fig.width = 10}
weather_scatterplot
```

